### ISSUE TITLE
Add Amplitude tracking to button clicks

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#1151]
- [x] Syncs
- [x] Resets
- [x] dbt task execution
- [x] Pipeline run
- [x] view logs in pipeline overview
- [x] view history in connections
- [x] view logs in connections
- [x] AI summary in connection
- [x] new task in transform
- [x] save new task in transform
- [x] save role change
- [x] data insights
- [x] data preview

**Comment by himanshudube97** [comment]
@fatchat  what is the "Resets" in the list.
